import { redirect } from "next/navigation";

import { auth } from "@/auth";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { SiteHeader } from "@/components/layout/side-header";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { Toaster } from "@/components/ui/sonner";
import SocketProvider from "@/context/SocketProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PrivateLayout({ children, modal }) {
  const session = await auth();

  if (!session) {
    return redirect("/login");
  }

  return (
    <SocketProvider>
      <SidebarProvider defaultOpen={false} className="flex flex-col">
        <SiteHeader />
        <div className="flex flex-1 overflow-x-hidden">
          <AppSidebar />
          <SidebarInset>
            <div className="flex flex-1 flex-col gap-4 p-4 overflow-x-hidden">{children}</div>
          </SidebarInset>
        </div>
        <Toaster />
      </SidebarProvider>
      {modal}
    </SocketProvider>
  );
}
